import type { Course, Lesson } from './types.js';
import type { PracticeProtocol } from '../domain/practice-types.js';

const rep=(focus:string,bpm=72):PracticeProtocol=>({kind:'repertoire',focus,measures:'8 bars',hands:'not-applicable',pulse:{bpm,beats:4,beatUnit:4,subdivision:1}});
const tempo=(technique:string,bpm=72,subdivision:1|2|3|4=1):PracticeProtocol=>({kind:'tempo',technique,pulse:{bpm,beats:4,beatUnit:4,subdivision}});
const groove=(style:string,focus:'time'|'muting'|'articulation'|'coordination',progression:string,bpm=72):PracticeProtocol=>({kind:'groove',style,focus,progression,key:'C',pulse:{bpm,beats:4,beatUnit:4,subdivision:2}});
const chords=(chordNames:string[],bpm=70):PracticeProtocol=>({kind:'chord-changes',chords:chordNames,target:16,technique:'Connect the voicings without dropping the pulse.',pulse:{bpm,beats:4,beatUnit:4,subdivision:1}});
const reading=(material:string,hands:'left'|'right'|'together'|'not-applicable'='not-applicable',bpm=60):PracticeProtocol=>({kind:'sight-reading',material,key:'C',hands,firstRead:false,pulse:{bpm,beats:4,beatUnit:4,subdivision:1}});
const pitch=(interval:number):PracticeProtocol=>({kind:'pitch-match',rootMidi:60,interval,target:6});

function lesson(input:{
  id:string;title:string;skill:string;objective:string;teaching:[string,string];example:string;
  isolate:string;apply:string;isolateProtocol:PracticeProtocol;applyProtocol:PracticeProtocol;
  checks:[string,string,string];question:string;options:[string,string,string];answer:number;explanation:string;
  easier:string;harder:string;mistake:string;transfer:string;
}):Lesson{
  return {
    id:input.id,title:input.title,skill:input.skill,objective:input.objective,teaching:[...input.teaching],
    example:{caption:'Worked example · '+input.title,text:input.example},
    tasks:[
      {id:'isolate',title:'Isolate: '+input.title,instructions:input.isolate,protocol:input.isolateProtocol,weight:2},
      {id:'apply',title:'Apply: '+input.title,instructions:input.apply,protocol:input.applyProtocol,weight:3},
    ],
    checks:[...input.checks],
    questions:[{prompt:input.question,options:[...input.options],answer:input.answer,explanation:input.explanation}],
    easier:input.easier,harder:input.harder,mistake:input.mistake,transfer:input.transfer,
  };
}

const drums:Course={
  id:'drums-repertoire-lab',revision:1,instrument:'drums',stage:'ensemble',level:'advanced',
  title:'Drums: repertoire laboratory',summary:'Turn timing, dynamics and coordination into repeatable song-section and rehearsal decisions.',
  prerequisites:'Comfortable basic grooves, fills and section counting; use your own or permitted repertoire audio when available.',
  outcomes:['Build repeatable section-specific drum parts','Shape dynamics without losing pulse','Repair transitions and complete uninterrupted takes'],
  placement:['I can count a full song form while playing.','I can simplify a groove without losing its identity.','I can identify one specific repair after a complete take.'],
  sourceIds:['berklee-drums','pas','ensemble'],
  lessons:[
    lesson({id:'section-map',title:'Map the drum role by section',skill:'repertoire',objective:'Create one stable drum intention for each section before adding fills or variations.',
      teaching:[
        'A dependable repertoire part begins with form and role rather than with the most interesting fill. Mark each section, decide the essential pulse source, backbeat location, kick anchors, and dynamic level, then play the simplest version that makes those decisions audible. This reduces accidental variation and makes rehearsal feedback easier to apply.',
        'Treat a section change as a musical event with a clear before and after state. The chorus may need more cymbal energy or a wider kick pattern, but the transition should not erase beat one. Practice the final bar of one section and the first bar of the next before attempting the whole song.'
      ],example:'Verse: closed hat eighths, snare 2/4, sparse kick. Chorus: stronger backbeat, ride or open hat, one extra kick anchor. Transition drill: Verse bar 8 → Chorus bar 1, then return to the simple verse.',
      isolate:'Choose two adjacent sections from your repertoire. Play the final bar of section A and first bar of section B six times with no optional fill.',apply:'Play both complete sections in sequence twice. Keep the chosen role consistent and write one transition observation.',isolateProtocol:tempo('Section-boundary pulse',70,2),applyProtocol:rep('Two-section drum arrangement',70),
      checks:['The section roles were clearly different without random extra notes.','Beat one remained stable through the boundary.','I could repeat the same arrangement decision on the second pass.'],
      question:'What should be defined before adding optional fills?',options:['The essential section role and pulse','The loudest possible crash','A different groove every pass'],answer:0,explanation:'A stable section role gives fills and variations a musical context instead of letting them replace the underlying arrangement.',
      easier:'Use only hi-hat, snare and one kick anchor in both sections, changing dynamics rather than note density.',harder:'Add one planned one-beat transition figure while preserving the same downbeat and section roles.',mistake:'Changing several groove layers at once can hide which transition detail caused the timing problem; simplify first.',transfer:'Use the same section-role map when preparing a worship set, rehearsal chart or any multi-section arrangement.'}),
    lesson({id:'dynamic-arc',title:'Shape a dynamic arc without rushing',skill:'dynamics',objective:'Increase and reduce drum-set intensity while preserving the same underlying pulse.',
      teaching:[
        'Louder playing often creates larger motions and can pull attacks ahead of the pulse. Build intensity with deliberate orchestration and controlled stroke height instead of simply hitting harder. First keep the rhythm identical across quiet, medium and strong versions so timing changes are easy to hear.',
        'A useful dynamic arc also includes the return. Practice moving from a stronger chorus texture back into a quieter verse without an extra crash, late hi-hat change or shortened final beat. The goal is repeatable contrast that still leaves room for the rest of the ensemble.'
      ],example:'Four-bar arc: bar 1 quiet closed hat → bar 2 medium → bar 3 stronger ride/crash texture → bar 4 controlled reduction. Keep snare on 2/4 and the same counted quarter-note pulse throughout.',
      isolate:'Play the same two-bar groove at three planned intensity levels. Do not change the kick pattern while comparing timing.',apply:'Perform an eight-bar quiet-to-strong-to-quiet arc and keep the final two bars as controlled as the first two.',isolateProtocol:tempo('Dynamic-level timing control',72,2),applyProtocol:rep('Eight-bar dynamic arc',72),
      checks:['The pulse stayed stable as stroke size or orchestration changed.','The quieter notes remained intentional rather than disappearing.','The return to the softer texture happened on the planned bar line.'],
      question:'What is the safest first comparison when testing dynamics?',options:['Keep the rhythm constant and change intensity','Add fills while getting louder','Increase tempo with volume'],answer:0,explanation:'Holding the rhythm constant isolates the dynamic change and makes timing or control differences easier to identify.',
      easier:'Use one surface and only two volume levels while counting aloud.',harder:'Change both orchestration and intensity at a section boundary while retaining the same pulse and backbeat.',mistake:'Equating intensity with maximum force can create rushing and tension; use orchestration and controlled motion instead.',transfer:'Apply the arc to a verse, build, chorus and return while listening for space around vocals or other lead material.'}),
    lesson({id:'fill-budget',title:'Give fills a fixed musical budget',skill:'fills',objective:'Place short fills inside the form without stealing time from the following downbeat.',
      teaching:[
        'A fill needs a defined start and end. Decide whether the fill owns one beat, two beats or one full bar, then count the remaining bar around it. Practicing the fill alone is incomplete because the most important event is often the groove note immediately after the fill.',
        'Use a limited vocabulary and vary orchestration later. A simple subdivision played confidently through the boundary is more useful than a complex phrase that makes the next section late. Reconnect the fill to at least one bar before and one bar after it.'
      ],example:'Two-beat fill budget: groove through beat 2, fill on 3 e & a 4 e & a, crash or groove on next beat 1. Repair loop: previous bar → fill bar → next bar.',
      isolate:'Loop one bar of groove, a two-beat fill, and the following beat one. Repeat until the return is stable before changing the fill.',apply:'Play an eight-bar phrase with exactly one planned fill in bar eight. Repeat the phrase using the same fill location.',isolateProtocol:tempo('Fill-to-downbeat control',68,4),applyProtocol:rep('Eight-bar phrase with one fill',68),
      checks:['The fill began at the planned count rather than early.','The next beat one arrived without hesitation.','The second phrase used the same fill location and budget.'],
      question:'Which event best reveals whether a fill was musically controlled?',options:['The first groove note after the fill','The fastest note inside the fill','The loudest tom'],answer:0,explanation:'The return to the groove shows whether the fill preserved the form and pulse instead of consuming extra time.',
      easier:'Use quarter or eighth notes for a one-beat fill and focus only on the return.',harder:'Keep the same rhythmic fill but orchestrate it differently on a second pass without changing its duration.',mistake:'Practicing only the fill can hide a late return; always include material before and after the transition.',transfer:'Use a fixed fill budget at real section changes so arrangement cues stay repeatable for the whole band.'}),
    lesson({id:'full-take',title:'Complete take, targeted repair, retake',skill:'assessment',objective:'Use a complete repertoire take to choose one bounded repair and verify it in a second take.',
      teaching:[
        'A full take reveals form, recovery and attention problems that isolated loops cannot. Do not stop for every small miss. Mark the moment mentally, finish the arrangement, then choose one repair based on musical impact and recurrence rather than frustration.',
        'The repair should be short enough to repeat accurately: often one or two bars before the problem through one bar after it. After focused repetitions, retake the whole song or section. The second take tests whether the repair survives its real entrance and context.'
      ],example:'Take 1 → note: chorus entry rushed. Repair loop: last verse bar + first two chorus bars, six controlled repeats. Take 2 → compare only the chorus entry and overall continuity before choosing another issue.',
      isolate:'Choose the highest-impact problem from one completed take and practice a two-to-four-bar window around it six times.',apply:'Perform another complete take without stopping. Compare the selected repair point with the first take and write one next step.',isolateProtocol:rep('Targeted repertoire repair',72),applyProtocol:rep('Complete repertoire retake',72),
      checks:['I completed the first take before choosing the repair.','The repair window included the real entrance into the problem.','The second take tested the same issue in full context.'],
      question:'What should determine the first repair after a take?',options:['A specific recurring or high-impact issue','The first note that felt imperfect','The hardest possible technique'],answer:0,explanation:'A bounded high-impact repair turns the take into actionable evidence while avoiding endless restarting for minor events.',
      easier:'Use one song section instead of a complete song and repair only one transition.',harder:'Run two complete takes separated by one repair window and compare consistency at the target point.',mistake:'Stopping repeatedly during the take prevents assessment of form and recovery; finish first, then repair.',transfer:'Use the same take-repair-retake cycle before rehearsal, performance preparation or recording a personal reference take.'}),
  ]
};

const guitar:Course={
  id:'guitar-repertoire-lab',revision:1,instrument:'guitar',stage:'ensemble',level:'advanced',
  title:'Guitar: repertoire and arrangement lab',summary:'Build repeatable parts, transitions and texture choices around real song sections.',
  prerequisites:'Comfortable chord changes, basic rhythm control and at least one song or arrangement you are allowed to practice.',
  outcomes:['Choose section-specific guitar textures','Repair transitions without losing pulse','Complete takes with controlled rhythm and space'],
  placement:['I can hold a consistent rhythm part for a complete section.','I can change chord shapes without stopping the count.','I can describe when a guitar part should become simpler.'],
  sourceIds:['justin','berklee-guitar','ensemble'],
  lessons:[
    lesson({id:'texture-map',title:'Choose one texture per section',skill:'repertoire',objective:'Assign a repeatable guitar texture to each song section and preserve its rhythmic role.',
      teaching:['A useful arrangement gives the guitar a clear job. Decide whether the section needs open chords, a muted pulse, a higher triad texture, single-note support or deliberate silence. Keeping one primary texture per section makes contrast audible and reduces random changes that distract from the song.','Before adding embellishment, test the texture through the section boundary. Chord changes, register changes and pickup figures should all fit inside the counted bar. If the transition consistently breaks the pulse, simplify the final chord or remove the pickup.'],
      example:'Verse: low open-chord eighths with light muting. Chorus: higher triads or broader strums. Bridge: sparse sustained shapes. Drill the final verse bar into the first chorus bar before playing the full form.',
      isolate:'Choose two adjacent sections and loop their boundary with only the essential chord shapes and rhythm.',apply:'Play both sections twice using the same planned texture choices and no unplanned fills.',isolateProtocol:chords(['C','Am','F','G'],68),applyProtocol:rep('Two-section guitar arrangement',68),
      checks:['Each section had one recognizable primary texture.','Chord changes stayed inside the counted bar.','The second pass repeated the same arrangement choices.'],question:'Why define a primary texture for each section?',options:['To create repeatable arrangement contrast','To avoid listening to the ensemble','To use every chord shape learned'],answer:0,explanation:'A repeatable texture gives the section a clear role and makes later embellishments easier to evaluate in context.',
      easier:'Use one familiar chord shape family and create contrast only with muting and dynamics.',harder:'Use two registers or voicing families while keeping the same harmonic rhythm and section entrances.',mistake:'Changing voicing, rhythm and register at the same time can make the transition unstable; simplify one variable.',transfer:'Use the texture map when preparing rhythm guitar for a worship set, acoustic arrangement or band rehearsal.'}),
    lesson({id:'rhythm-consistency',title:'Keep the strumming engine through changes',skill:'rhythm',objective:'Preserve continuous subdivision motion while changing harmony and dynamics.',
      teaching:['The picking or strumming motion can act as a physical reference for subdivision even when some strokes do not contact the strings. Practice the motion separately, then let chord changes happen inside that motion instead of pausing the hand to rebuild each shape.','Dynamics should not require a new tempo. Use smaller or larger contact and selective muting while the underlying subdivision remains stable. Record or listen back when possible because a visually continuous hand can still produce uneven attacks.'],
      example:'Count 1 & 2 & 3 & 4 &. Keep down-up motion throughout. Change C → Am on the next beat 1 without stopping the hand; repeat with a quieter verse pass and stronger chorus pass.',
      isolate:'Loop two chord changes while keeping continuous eighth-note motion; mute the strings if necessary to preserve the count.',apply:'Play an eight-bar progression with a planned quiet first half and stronger second half without changing tempo.',isolateProtocol:chords(['C','Am','F','G'],72),applyProtocol:rep('Eight-bar dynamic rhythm part',72),
      checks:['The subdivision motion continued through chord changes.','The stronger section did not rush.','Muted or omitted strokes were intentional rather than pauses.'],question:'What should stay constant when the guitar part becomes louder?',options:['The underlying pulse and subdivision','The exact physical force of every stroke','The chord register'],answer:0,explanation:'Dynamic contrast is useful only when the rhythmic reference remains stable enough for the ensemble to trust the part.',
      easier:'Mute all strings and practice the continuous down-up motion before adding chord shapes.',harder:'Add syncopated omissions while keeping the same hand motion and clean chord entrances.',mistake:'Freezing the strumming hand during chord changes creates a hidden pause even if the next chord eventually sounds correct.',transfer:'Carry the continuous subdivision reference into songs with sparse accents, syncopation or changing dynamics.'}),
    lesson({id:'transition-window',title:'Repair chord and section transitions in context',skill:'technique',objective:'Use short contextual loops to make difficult repertoire transitions repeatable.',
      teaching:['A difficult chord or lead phrase often fails because of its entrance or exit rather than the notes alone. Build a repair window that starts before the problem and ends after it. This preserves the timing cue that triggers the movement and the recovery required for the next musical event.','Slow the passage only enough to keep the intended fingering and rhythm. After several clean repetitions, raise the rate in small steps or return directly to the song tempo if the issue was coordination rather than speed. Avoid practicing an isolated shape that never occurs by itself in the arrangement.'],
      example:'Problem: G → D/F# into chorus. Repair window: final two beats of G, full D/F# bar, first beat of Em. Repeat at 80%, then test the same window inside the complete verse-to-chorus transition.',
      isolate:'Choose one difficult repertoire transition and repeat a short window containing the event before and after it.',apply:'Play the full surrounding section twice and evaluate whether the repaired transition survives its original entrance.',isolateProtocol:chords(['G','D/F#','Em'],64),applyProtocol:rep('Contextual guitar transition retest',72),
      checks:['The loop included material before and after the difficult event.','The movement stayed rhythmically connected at the chosen tempo.','The full-section retest used the same fingering or voicing decision.'],question:'Why include notes before and after the difficult change?',options:['They provide the real entrance and recovery context','They make the exercise longer for its own sake','They guarantee a higher BPM'],answer:0,explanation:'Context determines when the movement begins and what must follow, so an isolated shape can succeed while the real transition still fails.',
      easier:'Use only the final beat before and first beat after the change at a slower rate.',harder:'Retest the transition from a longer phrase without changing the repaired fingering strategy.',mistake:'Repeating only the destination chord may improve the shape but not the timed movement into and out of it.',transfer:'Use contextual repair windows for riffs, lead phrases, capo changes and any repeated section boundary.'}),
    lesson({id:'full-take',title:'Arrange, take, repair, retake',skill:'assessment',objective:'Complete a guitar take, choose one musical repair, and verify it without adding new variables.',
      teaching:['A repertoire take should test the part you intend to perform, not a constantly changing practice version. Decide the texture, chord shapes, capo and major rhythmic choices before starting, then finish the take unless something makes continuation impossible.','After the take, select one repair based on impact: form, pulse, transition, unwanted noise or an arrangement choice that covered another part. Practice a short window, then retake without changing several other details. This creates comparable evidence rather than two unrelated performances.'],
      example:'Take 1: verse stable, chorus entry noisy. Repair: last verse bar → first chorus bar, six repeats. Take 2: same capo, shapes and rhythm; compare only entry cleanliness and continuity.',
      isolate:'Repair one high-impact issue from a complete take using a short contextual loop.',apply:'Play another complete take with the same arrangement choices and compare the repaired point.',isolateProtocol:rep('Targeted guitar repertoire repair',70),applyProtocol:rep('Complete guitar repertoire retake',70),
      checks:['I completed a meaningful take before selecting the repair.','The repair addressed one specific musical issue.','The retake kept the same main arrangement choices for a fair comparison.'],question:'What makes two takes useful to compare?',options:['Keeping the main arrangement variables stable','Changing every voicing between takes','Only comparing the fastest passage'],answer:0,explanation:'Stable arrangement variables make it possible to judge whether the targeted repair actually improved the same musical situation.',
      easier:'Use one complete song section rather than the entire arrangement.',harder:'Retake the full form from memory while preserving the same section textures and transition decisions.',mistake:'Adding new embellishments during the retake can hide whether the original repair worked.',transfer:'Use the same take-repair-retake process before rehearsal, recording demos or preparing a live acoustic part.'}),
  ]
};

const bass:Course={
  id:'bass-repertoire-lab',revision:1,instrument:'bass',stage:'ensemble',level:'advanced',
  title:'Bass: repertoire and pocket lab',summary:'Turn note length, harmonic anchors and drummer relationships into dependable song parts.',
  prerequisites:'Comfortable root/chord-tone playing, muting and steady eighth-note or quarter-note time.',
  outcomes:['Design stable section bass parts','Coordinate selectively with drums','Control note length and transition timing through full takes'],
  placement:['I can follow the song form without losing roots.','I can deliberately shorten or sustain notes.','I can simplify when the arrangement becomes crowded.'],
  sourceIds:['studybass','muting','ensemble'],
  lessons:[
    lesson({id:'anchor-map',title:'Map harmonic and rhythmic anchors',skill:'repertoire',objective:'Define the minimum bass events that make each section harmonically and rhythmically dependable.',
      teaching:['Start with the smallest part that clearly communicates the harmony and pulse. Mark chord-change beats, important kick or ensemble anchors, and planned releases. This anchor map is the version you can return to whenever a busier line becomes unstable.','Once the anchors are dependable, optional approach notes or syncopations can be judged by whether they improve the phrase. An extra note that makes the next chord late is not an upgrade. Compare the decorated version directly with the anchor version at the same tempo.'],
      example:'Verse anchor: root on beat 1, optional fifth on 3, planned release before next chord. Chorus anchor: roots on 1/3 plus one shared offbeat with kick. Keep a written minimal version for recovery.',
      isolate:'Play a four-chord loop using only the minimum root anchors and planned note endings.',apply:'Play the same loop with one optional rhythmic or chord-tone addition, then return immediately to the anchor version.',isolateProtocol:groove('Minimal bass anchors','muting','C – Am – F – G',68),applyProtocol:rep('Anchor plus one bass variation',68),
      checks:['Every chord change landed on the intended root or agreed target.','Note endings were as deliberate as note starts.','I could return to the minimal anchor version without hesitation.'],question:'What is the purpose of an anchor version?',options:['A dependable minimum part for form and pulse','A rule that forbids all variation','A way to maximize note density'],answer:0,explanation:'A minimal anchor part preserves the essential harmony and timing, giving variations a stable reference and recovery point.',
      easier:'Use one whole-note root per bar and focus only on clean changes and releases.',harder:'Add one chord tone or shared drum accent while preserving every original anchor and release.',mistake:'Adding passing notes before the chord-change timing is stable can make harmony arrive late even when the notes are correct.',transfer:'Use an anchor map for unfamiliar rehearsal material so you can support the song before refining the bass line.'}),
    lesson({id:'kick-relationship',title:'Coordinate with kick without copying it',skill:'ensemble',objective:'Choose deliberate shared attacks with the kick while keeping an independent bass phrase.',
      teaching:['Bass and kick often benefit from shared anchors, but copying every kick note can make the bass part crowded or harmonically awkward. Identify the strongest shared events—often beat one, section entrances or one characteristic syncopation—then let each instrument keep its own remaining role.','Practice both relationships: a sparse version with only major anchors and a coordinated version with one additional shared offbeat. The better choice depends on the arrangement, not on how many notes match. Keep note lengths audible because a bass release can change the feel even when the attack aligns.'],
      example:'Kick: 1, & of 2, 3. Bass A: roots on 1 and 3. Bass B: add & of 2 only where it supports the phrase. Compare both against the same counted drum pattern.',
      isolate:'Speak or tap a simple kick pattern while playing only shared beat-one and beat-three bass anchors.',apply:'Add one agreed offbeat to the bass line and compare whether the groove becomes clearer or busier.',isolateProtocol:groove('Bass-kick anchor study','time','C – F – C – G',72),applyProtocol:rep('Selective bass-kick coordination',72),
      checks:['The shared attacks aligned without pulling later notes early.','The bass still communicated the chord changes independently.','I could explain why the added shared note helped or did not help.'],question:'Does good bass-kick coordination require identical patterns?',options:['No, selected anchors can be enough','Yes, every note must match','Only at slow tempos'],answer:0,explanation:'Coordination is an intentional relationship between parts; identical rhythms are one option, not a universal requirement.',
      easier:'Share only beat one and keep the rest of the bass part as sustained roots.',harder:'Maintain an independent bass anticipation while preserving two stable shared kick anchors.',mistake:'Trying to mirror every kick can obscure harmonic movement and make the bass line busier than the arrangement needs.',transfer:'Discuss shared attacks with a drummer during rehearsal instead of assuming complete rhythmic duplication.'}),
    lesson({id:'length-contrast',title:'Use note length as arrangement contrast',skill:'articulation',objective:'Create section contrast by changing note duration without losing harmonic timing.',
      teaching:['Bass arrangement changes do not always require more notes. A verse can use shorter controlled releases while a chorus uses longer notes, or the reverse. Compare the effect of duration while keeping pitch and attack placement constant so you hear what note length actually contributes.','Muting must be planned with the next event. A short note should end at a defined point rather than simply decaying unpredictably. Long notes should not ring across chord changes unless that overlap is intentional and harmonically appropriate.'],
      example:'Same roots, two textures: A) root on beat 1, release before beat 3. B) root on beat 1, sustain to beat 4. Compare verse/chorus contrast without changing the chord progression.',
      isolate:'Play one four-bar progression twice: first with short roots, then with sustained roots, keeping attack timing unchanged.',apply:'Assign one note-length texture to verse and the other to chorus, then play the transition twice.',isolateProtocol:groove('Bass note-length contrast','articulation','C – Am – F – G',66),applyProtocol:rep('Verse-to-chorus note-length arrangement',66),
      checks:['The attack timing stayed stable in both note-length versions.','Short notes ended at intentional counts.','Sustained notes stopped cleanly before incompatible chord changes.'],question:'What should stay fixed when comparing note-length textures?',options:['Pitch and attack placement','Every note must ring indefinitely','The number of chord changes'],answer:0,explanation:'Holding pitch and attacks constant isolates note duration so you can judge its arrangement effect rather than multiple changes at once.',
      easier:'Compare only two bars of one chord using quarter-note versus whole-note length.',harder:'Use contrasting lengths while adding one consistent approach note before each chord change.',mistake:'Uncontrolled ringing makes a long texture sound muddy and a short texture inconsistent; define the release count.',transfer:'Use note length to create verse/chorus contrast before increasing density or adding fills.'}),
    lesson({id:'full-take',title:'Pocket take, repair, retake',skill:'assessment',objective:'Complete a bass take and verify one timing, muting or harmonic repair in a second take.',
      teaching:['A full bass take tests form, recovery, note endings and consistency in ways a short loop cannot. Keep going through small errors so you can identify whether the main problem is local or whether the part gradually drifts away from the arrangement.','After the take, choose one repair: a late root, an unwanted ringing string, a transition, or a repeated timing tendency. Practice a short window and retake the same arrangement without adding new fills. Compare the selected issue and overall continuity, not a vague feeling of quality.'],
      example:'Take 1: chorus root arrives late after muted verse. Repair: final verse bar → first two chorus bars. Take 2: same line and register, compare root timing and clean release only.',
      isolate:'Repair one high-impact timing, muting or harmonic issue from a complete bass take.',apply:'Play a second complete take with the same core bass arrangement and evaluate the repaired point.',isolateProtocol:groove('Targeted bass repertoire repair','muting','C – Am – F – G',70),applyProtocol:rep('Complete bass repertoire retake',70),
      checks:['The first take was completed before choosing the repair.','The repair window included the real entrance into the problem.','The retake kept the same main line so the repair could be compared.'],question:'Why avoid adding new fills during the retake?',options:['They would change the comparison conditions','Bass fills are always wrong','They automatically increase tempo'],answer:0,explanation:'A retake is useful evidence when the main part stays stable enough to judge whether the selected repair changed the same musical problem.',
      easier:'Use one complete verse and chorus instead of the entire song.',harder:'Retake the complete arrangement while preserving planned note lengths, anchors and transition decisions from memory.',mistake:'Judging only attack accuracy can miss ringing strings and poor releases that affect the pocket just as strongly.',transfer:'Use the take-repair-retake process before band rehearsal, service sets or recording a bass reference track.'}),
  ]
};

const piano:Course={
  id:'piano-repertoire-lab',revision:1,instrument:'piano',stage:'ensemble',level:'advanced',
  title:'Piano: repertoire and accompaniment lab',summary:'Build section textures, voice-leading and complete accompaniment takes around real repertoire.',
  prerequisites:'Comfortable chord shapes, basic scale/key knowledge and simple two-hand accompaniment.',
  outcomes:['Choose stable accompaniment textures','Connect chords with economical voice-leading','Repair transitions and complete full-form takes'],
  placement:['I can play a chord progression without stopping.','I can keep a left-hand pulse under a right-hand texture.','I can simplify accompaniment when another part needs space.'],
  sourceIds:['berklee-piano','berklee-reading','ensemble'],
  lessons:[
    lesson({id:'texture-map',title:'Assign accompaniment textures by section',skill:'repertoire',objective:'Choose repeatable piano textures that support each section without changing harmony or pulse accidentally.',
      teaching:['An accompaniment part should have a deliberate density, register and rhythmic role. Map each section before adding decorations: perhaps whole or half-note chords in the verse, a stronger eighth-note pattern in the chorus, and sparse sustained voicings under a vocal bridge. The contrast should serve the arrangement, not demonstrate every available technique.','Practice the transition between textures directly. Changing register, pedal, hand pattern and dynamics simultaneously can create a break in pulse, so reduce the number of moving variables until the boundary is secure. Then restore the intended texture one element at a time.'],
      example:'Verse: LH roots + RH sustained triads. Chorus: LH roots/fifths + RH repeated eighth-note chords. Bridge: high RH pads with minimal LH. Drill final verse bar → first chorus bar before running the form.',
      isolate:'Choose two section textures and repeat their boundary with simplified voicings until the pulse stays continuous.',apply:'Play both complete sections twice using the same mapped textures and planned register changes.',isolateProtocol:chords(['C','Am','F','G'],66),applyProtocol:rep('Two-section piano accompaniment map',66),
      checks:['Each section used a recognizable planned texture.','The transition kept a continuous count.','The second pass repeated the same register and density decisions.'],question:'What should guide accompaniment density?',options:['The arrangement and other musical roles','The number of techniques you know','Maximum notes per bar'],answer:0,explanation:'Accompaniment works when its density and register support the arrangement rather than competing with other important parts.',
      easier:'Use block chords in both sections and create contrast only with register and dynamics.',harder:'Change voicing inversion and rhythmic texture together while keeping the bass movement and pulse stable.',mistake:'Adding pedal, wider voicings and more rhythm simultaneously can hide the actual cause of a broken transition.',transfer:'Use the section-texture map when preparing keys for worship, singer accompaniment or small ensemble rehearsal.'}),
    lesson({id:'voice-leading',title:'Move the smallest useful distance',skill:'harmony',objective:'Connect accompaniment chords with economical common tones and controlled register.',
      teaching:['Voice-leading can make a progression smoother without changing its harmonic function. Look for common tones and nearby chord tones so the right hand does not jump to a fresh root-position shape on every chord. Keep the bass role separate enough that the harmony remains clear.','Economical movement is not always the only musical choice, but it is a useful baseline. Compare a root-position version with a closer-voiced version at the same tempo and listen to continuity, top-note line and hand preparation rather than assuming one is automatically superior.'],
      example:'C: C-E-G → Am: C-E-A → F: C-F-A → G: B-D-G. The upper hand can retain common tones while the bass or lowest note identifies the harmonic movement.',
      isolate:'Move through C–Am–F–G using close right-hand voicings. Pause only after the bar, not during the chord change.',apply:'Use those voicings in an eight-bar accompaniment pattern with a simple left-hand root pulse.',isolateProtocol:chords(['C','Am','F','G'],62),applyProtocol:rep('Close-voiced accompaniment progression',62),
      checks:['Common tones remained in place where practical.','Chord changes occurred on the intended beat.','The top voice formed a controlled line rather than random large jumps.'],question:'What is one benefit of keeping common tones between chords?',options:['Reduced unnecessary motion and smoother connection','It changes every chord into the same harmony','It guarantees louder dynamics'],answer:0,explanation:'Retaining common tones can reduce hand movement and create a smoother upper-voice connection while preserving the chord changes.',
      easier:'Practice only C → Am and F → G as separate two-chord movements.',harder:'Choose a deliberate top-note line while keeping the bass roots and harmonic rhythm unchanged.',mistake:'Searching for the closest shape after the beat arrives creates pauses; prepare the next voicing during the current bar.',transfer:'Use economical voice-leading to support singers or instruments without filling the arrangement with large register jumps.'}),
    lesson({id:'reading-to-repertoire',title:'Turn a chart into a playable accompaniment',skill:'reading',objective:'Convert chord symbols and form markers into a simple continuous accompaniment before elaborating.',
      teaching:['A chart gives information but not necessarily a complete piano part. First identify form, chord-change locations, repeats, stops and ending instructions. Build the simplest playable accompaniment that preserves those events before deciding on fills, inversions or rhythmic variation.','Keep a recovery strategy. If a voicing is missed, land on the next reliable chord or beat rather than stopping to reconstruct the previous one. Continuity is part of accompaniment skill, and a later repair can address the missed transition separately.'],
      example:'Chart: Intro 2 | Verse C Am F G | Chorus F C G G | stop 1 bar | return C. First pass: one block chord per written change plus counted silence. Second pass: add a simple repeated pattern.',
      isolate:'Read a short chord/form chart and play one simple chord event per written change without embellishment.',apply:'Play the complete chart with one chosen accompaniment texture and recover forward from small errors.',isolateProtocol:reading('Prepared chord-and-form chart', 'together',58),applyProtocol:rep('Complete prepared chart accompaniment',58),
      checks:['I followed the written form and stops correctly.','Chord changes happened at the written locations.','A small error did not force an unnecessary restart.'],question:'What is the best first pass through a new accompaniment chart?',options:['A simple part that preserves form and harmony','Maximum fills and inversions','Ignoring repeat and stop markings'],answer:0,explanation:'A simple accurate pass establishes the form and harmonic timing that later texture and voicing decisions depend on.',
      easier:'Use one hand and one chord per bar on a four-chord form.',harder:'Add inversions or rhythmic comping while preserving every repeat, stop and ending instruction.',mistake:'Decorating before the form is dependable can make it difficult to distinguish reading mistakes from technique problems.',transfer:'Use the same chart-to-minimum-part method when covering unfamiliar repertoire in rehearsal.'}),
    lesson({id:'full-take',title:'Accompaniment take, repair, retake',skill:'assessment',objective:'Complete a piano accompaniment take and verify one contextual repair in the next take.',
      teaching:['A complete accompaniment take tests form memory, texture consistency, transitions and recovery. Keep the planned voicings and section textures stable enough that the result represents the arrangement you intend to use rather than a stream of new experiments.','Afterward choose one high-impact issue—late chord, broken hand pattern, pedal blur, wrong form turn or crowded register. Repair a short contextual window and retake. The second take should test the same arrangement conditions so the comparison is meaningful.'],
      example:'Take 1: bridge entry breaks because RH jumps register. Repair final chorus bar → first two bridge bars with prepared hand position. Take 2: same textures and voicings, compare bridge continuity.',
      isolate:'Repair one high-impact accompaniment issue using a short section-transition or chord-change window.',apply:'Play another complete accompaniment take with the same core arrangement and compare the target issue.',isolateProtocol:chords(['F','C','G','Am'],60),applyProtocol:rep('Complete piano accompaniment retake',60),
      checks:['I completed a meaningful take before choosing the repair.','The repair included the real musical entrance into the problem.','The retake kept the same main textures and voicing plan.'],question:'Why keep the main arrangement stable during the retake?',options:['So the repaired issue can be compared under the same conditions','Because variation is always prohibited','To avoid listening to the result'],answer:0,explanation:'Stable conditions make the second take useful evidence about the selected repair rather than a completely different arrangement.',
      easier:'Use one verse and chorus instead of the full song form.',harder:'Retake from memory while preserving section textures, voicing strategy, stops and ending cues.',mistake:'Changing several textures after the first take makes it unclear whether the original repair actually improved.',transfer:'Apply the same process to rehearsal charts, singer accompaniment, worship keys or personal arrangement practice.'}),
  ]
};

const voice:Course={
  id:'voice-repertoire-lab',revision:1,instrument:'voice',stage:'ensemble',level:'advanced',
  title:'Voice: repertoire and ensemble lab',summary:'Apply comfortable technique, phrasing, harmony and recovery to complete repertoire takes.',
  prerequisites:'A personally comfortable range, ability to stop for symptoms, and short repertoire phrases that can be sung without strain.',
  outcomes:['Plan breaths and dynamics around phrases','Prepare entrances and harmony parts','Use complete takes without singing through warning signs'],
  placement:['I can mark comfortable breath points before singing.','I can reproduce a starting pitch from a reference.','I stop rather than push through pain or persistent hoarseness.'],
  sourceIds:['berklee-voice','nidcd','ensemble'],
  lessons:[
    lesson({id:'phrase-map',title:'Map breath, diction and intensity by phrase',skill:'repertoire',objective:'Plan breath points, diction priorities and intensity for a short repertoire section before repeating it.',
      teaching:['Repertoire practice is more efficient when phrasing decisions are made before repeated singing. Mark where the sentence naturally releases, where consonants need clarity and where the musical line can remain easier rather than continuously intense. Choose breath points that fit your current comfortable capacity instead of turning long phrases into endurance tests.','Speak the text rhythmically before singing if diction or breath timing is unclear. Then sing a short section at an easy level and evaluate whether the planned breaths preserved the phrase. Rework the plan if you need to grab air, tense the neck or sacrifice words to reach the end.'],
      example:'Four-line section: mark breath after line 1 and line 3, underline two consonants that carry the text, circle one dynamic peak. Speak on the pulse first, then sing only the four lines once at comfortable volume.',
      isolate:'Speak and then lightly sing one short phrase using the marked breath and diction plan. Rest between attempts.',apply:'Sing the complete short section once, then compare actual breath points with the written plan before repeating.',isolateProtocol:rep('Comfortable phrase map'),applyProtocol:rep('Short repertoire phrase with planned breaths'),
      checks:['The planned breath points were comfortable and usable.','Diction stayed clear without extra jaw or neck effort.','No pain, hoarseness, or rising fatigue was present.'],question:'What should decide a breath point?',options:['The phrase and your current comfortable capacity','The longest breath you can force','Avoiding all breaths until the section ends'],answer:0,explanation:'Breath planning should support the phrase within comfortable current capacity rather than treating breath length as an endurance contest.',
      easier:'Speak the phrase and sing only half of it before resting.',harder:'Keep the same breath map while adding one planned dynamic rise and return at comfortable volume.',mistake:'Pushing past a planned breath because the previous attempt lasted longer can add unnecessary tension and reduce clarity.',transfer:'Mark breath and diction plans directly in your permitted score or lyric sheet before rehearsal.'}),
    lesson({id:'entrance',title:'Prepare reliable entrances from a reference',skill:'pitch',objective:'Hear and reproduce a starting pitch or interval before entering a repertoire phrase.',
      teaching:['Many vocal entrances fail before the phrase begins because the reference pitch, interval or count was not internalized. Separate the setup: hear the reference, imagine the target, reproduce it briefly, then place the lyric entrance in time. Do not repeatedly sing the whole phrase while still uncertain about the first pitch.','Use a comfortable key and volume. If the target interval lies outside your chosen range, change the reference rather than reaching. After the entrance is dependable by itself, reconnect the next few notes so the preparation does not create a pause in the actual music.'],
      example:'Reference root → hear the target third → reproduce target on a neutral syllable → count one bar → sing the lyric entrance plus the next three notes. Rest, then repeat only if the voice still feels easy.',
      isolate:'Use the reference pitch to reproduce a comfortable major-third entrance, with rest between attempts.',apply:'Place the same prepared entrance at the start of a short lyric phrase after a counted bar.',isolateProtocol:pitch(4),applyProtocol:rep('Prepared vocal repertoire entrance'),
      checks:['The target pitch was heard before I sang it.','The lyric entrance followed the counted timing without a pause.','No pain, hoarseness, or rising fatigue was present.'],question:'What should happen before repeatedly singing an uncertain entrance?',options:['Isolate the reference and target first','Increase volume until the pitch appears','Repeat the entire song immediately'],answer:0,explanation:'Separating the starting pitch and interval reduces unnecessary full-phrase repetition and makes the actual entrance problem clearer.',
      easier:'Match only the reference pitch before adding the target interval.',harder:'Prepare the entrance after a longer silent count or from a different comfortable reference pitch.',mistake:'Sliding around for the pitch during every full phrase can reinforce an uncertain entrance and add unnecessary repetitions.',transfer:'Use the same reference-hear-count-enter sequence for harmony entrances and exposed starts.'}),
    lesson({id:'harmony',title:'Hold a harmony line against another part',skill:'harmony',objective:'Maintain a short harmony phrase without drifting toward the melody or increasing vocal effort.',
      teaching:['Harmony practice should start with your line alone. Identify the first pitch, important interval relationships and any places where the line crosses or approaches the melody. Repeating the harmony while also trying to follow another singer before your own line is stable often causes unintentional melody copying.','Once the line is comfortable, add a permitted reference or partner at low enough level that you can still hear yourself. Focus on entrances, releases and pitch relationship rather than singing louder to compete. Stop if the part creates pain, persistent hoarseness or increasing fatigue.'],
      example:'Step 1: harmony line alone on a neutral syllable. Step 2: lyric at easy volume. Step 3: add melody reference for one short phrase. Step 4: stop and note where the line pulled toward the melody.',
      isolate:'Practice one short harmony line alone from a comfortable starting pitch and rest before repeating.',apply:'Sing the harmony once against a permitted melody reference or partner, then write one specific drift or entrance observation.',isolateProtocol:pitch(4),applyProtocol:rep('Short harmony line against reference'),
      checks:['I could reproduce my harmony line alone before adding another part.','I kept my own entrance and release rather than following the melody automatically.','No pain, hoarseness, or rising fatigue was present.'],question:'Why learn the harmony line alone first?',options:['To establish its own pitches and timing before adding interference','Because harmony should always be louder','To avoid listening to the melody entirely'],answer:0,explanation:'An independent line provides a stable reference; adding the melody afterward tests whether that line can be maintained in ensemble context.',
      easier:'Use only the first two harmony notes against a quiet reference.',harder:'Sing a longer phrase while preserving independent note endings and a comfortable dynamic level.',mistake:'Trying to overpower the reference can increase effort without improving pitch independence; reduce level and shorten the phrase.',transfer:'Prepare harmony entrances and releases separately before ensemble rehearsal so group repetitions stay efficient.'}),
    lesson({id:'full-take',title:'Comfortable take, targeted repair, retake',skill:'assessment',objective:'Complete a bounded repertoire take, choose one repair, and retake only while the voice remains comfortable.',
      teaching:['A take can reveal phrase planning, entrances, memory and expression, but vocal repetition has a physical cost. Choose a bounded section or song length that fits your current condition, include rests, and do not treat completing many takes as evidence of better practice. A single complete take can be enough to identify the next repair.','Choose one specific issue after the take: entrance, breath point, lyric clarity, harmony drift or phrasing. Repair a short window with rest, then retake only if the voice still feels comfortable. Pain, persistent hoarseness or rising fatigue ends the singing work; switch to listening, marking or rest rather than forcing another comparison.'],
      example:'Take 1: one verse + chorus. Observation: chorus entrance pitch uncertain. Repair: reference pitch + first line, three rested attempts. Retake verse + chorus only if voice remains easy; otherwise record the repair for another day.',
      isolate:'Repair one short repertoire issue with generous rest and comfortable volume.',apply:'Complete one bounded retake only if the voice remains comfortable, then compare the selected issue rather than total effort.',isolateProtocol:rep('Short vocal repertoire repair'),applyProtocol:rep('Bounded vocal repertoire retake'),
      checks:['The repair focused on one specific repertoire issue.','I rested between repeated singing attempts.','No pain, hoarseness, or rising fatigue was present.'],question:'What should happen if fatigue rises before the retake?',options:['Stop singing and switch to rest or non-vocal work','Push through to preserve the comparison','Sing louder so the take finishes sooner'],answer:0,explanation:'A comparison is not worth increasing vocal symptoms; stopping and returning later preserves safety and the usefulness of future practice.',
      easier:'Use one short phrase as both the take and repair target.',harder:'Prepare a longer section with planned breaths and harmony/entrance cues, but still stop at the first warning sign.',mistake:'Treating repeated complete takes as a stamina test can add fatigue without addressing the specific musical problem.',transfer:'Use bounded take-repair-retake cycles for rehearsal preparation while keeping rest and symptom monitoring explicit.'}),
  ]
};

const custom:Course={
  id:'custom-development',revision:1,instrument:'custom',stage:'development',level:'intermediate',
  title:'Practice method: repertoire application',summary:'A general, non-fabricated method course for applying an instrument-specific skill to real material with explicit evidence.',
  prerequisites:'A safe technique and task appropriate to your actual instrument, ideally chosen with a teacher or reliable method.',
  outcomes:['Define observable repertoire goals','Use contextual repair windows','Complete takes and distinguish evidence from confidence'],
  placement:['I can define one observable criterion for a passage.','I can isolate a short difficult event without losing its context.','I can complete a take without treating the timer as a proficiency score.'],
  sourceIds:['interleaving','spacing','ensemble'],
  lessons:[
    lesson({id:'target',title:'Define a repertoire target you can observe',skill:'planning',objective:'Turn a vague repertoire goal into one bounded passage and observable performance criterion.',
      teaching:['A useful practice target names the material, the condition and what you will observe. “Get better at the song” is difficult to evaluate, while “play bars 9–12 continuously with the intended rhythm and release” tells you what to attempt. The criterion must suit your actual instrument; Steadybar does not invent specialist technique for unknown instruments.','Choose one criterion at a time when possible: continuity, timing, target events, note endings, articulation or another teacher-approved feature. Keep safety constraints outside the scoring logic—pain or unsafe technique is a reason to stop regardless of whether the musical criterion was met.'],
      example:'Material: one four-bar phrase. Criterion: complete it without stopping while preserving the intended rhythm. Evidence: one actual take plus one written observation. Next repair is chosen only after that take.',
      isolate:'Write one bounded passage and one observable criterion, then attempt only that passage.',apply:'Place the passage back inside a longer phrase and judge the same criterion without changing it afterward.',isolateProtocol:rep('Bounded repertoire target'),applyProtocol:rep('Contextual repertoire target'),
      checks:['The target named specific material rather than a vague skill.','The criterion could be observed in an actual take.','I kept the criterion fixed while judging the attempt.'],question:'What makes a repertoire criterion useful?',options:['It describes an observable feature of bounded material','It changes after every attempt','It guarantees a professional grade'],answer:0,explanation:'A bounded observable criterion makes practice evidence interpretable without pretending the app can grade instrument-specific technique.',
      easier:'Use one or two events and a continuity-only criterion.',harder:'Use two related passages with the same criterion and compare which context changes the difficulty.',mistake:'Changing the criterion after seeing the result makes the evidence impossible to interpret consistently.',transfer:'Use the same target format in lessons or rehearsals so feedback addresses a specific passage and behavior.'}),
    lesson({id:'context-window',title:'Repair the event with its entrance and exit',skill:'repair',objective:'Practice a difficult event inside a small context window rather than as an isolated fragment only.',
      teaching:['Motor and musical problems often depend on what comes immediately before and after them. Include enough preceding material to trigger the real movement or preparation and enough following material to test recovery. The window should still be short enough for accurate, low-cost repetition.','If the event remains unstable, simplify one variable rather than making the loop longer. Slow the pulse, reduce note density or choose an easier technical version appropriate to your instrument. Return to the original context only after the simplified version is controlled.'],
      example:'Problem event = X. Window = two events before → X → one event after. Repeat the window six times, then test the same X inside the full phrase once. Record whether the entrance, event or exit still causes the problem.',
      isolate:'Choose one difficult event and repeat a short entrance-event-exit window at an appropriate difficulty.',apply:'Retest the same event inside the longer phrase and record which part of the window changed.',isolateProtocol:rep('Contextual repair window'),applyProtocol:rep('Full-phrase repair retest'),
      checks:['The window included a real entrance and exit.','The repetition stayed short enough to remain controlled.','The longer retest used the same target event and criterion.'],question:'Why include the entrance and exit around a problem?',options:['They can be part of what makes the event difficult','They automatically increase speed','They remove the need for repetition'],answer:0,explanation:'Context can determine preparation and recovery, so isolated success may not transfer unless the neighboring events are also practiced.',
      easier:'Use one event before and one after the target.',harder:'Retest the target from two different phrase entrances while keeping the same observable criterion.',mistake:'Expanding the loop after every error can turn a precise repair into another unfocused full run.',transfer:'Use contextual windows for repertoire transitions, technical shifts, entrances, releases or coordination changes.'}),
    lesson({id:'take',title:'Complete take before choosing the next repair',skill:'assessment',objective:'Use a complete bounded take to find the highest-value next repair without restarting for minor errors.',
      teaching:['A complete take provides evidence about continuity, form and recovery that repeated stopping cannot. Decide the bounded material first, then finish it unless safety or equipment makes continuation inappropriate. Small errors can be marked mentally and reviewed afterward rather than triggering automatic restarts.','After the take, choose one repair based on recurrence or musical impact. A timer confirms elapsed practice, not proficiency, and confidence alone is not evidence of correctness. Use the explicit criterion from the material and, where possible, external teacher or partner feedback.'],
      example:'Take: complete selected section once. Notes: one recurring transition disrupted continuity. Repair that window. Retake the same section with the same criterion, then stop and decide whether more work is useful today.',
      isolate:'Run one complete bounded take without restarting for minor errors; write the single highest-value repair afterward.',apply:'Practice that repair briefly, then complete one comparable retake and judge the original criterion.',isolateProtocol:rep('Complete bounded take'),applyProtocol:rep('Comparable repertoire retake'),
      checks:['I completed the bounded take before selecting the repair.','The repair addressed a recurring or high-impact issue.','The retake used the same criterion and comparable material.'],question:'What does completing the app timer prove by itself?',options:['Elapsed practice time, not proficiency','Correct instrument technique','Professional readiness'],answer:0,explanation:'Elapsed time is valid activity evidence, but most technical and musical correctness still requires explicit observation or external feedback.',
      easier:'Use a short phrase as the complete take.',harder:'Use a longer form while limiting the post-take repair to one issue before retesting.',mistake:'Restarting for every minor error hides recovery skill and makes it difficult to identify the most important recurring problem.',transfer:'Use complete takes strategically before lessons, rehearsals or personal recordings to generate specific questions and repairs.'}),
    lesson({id:'retain-transfer',title:'Return later and transfer the repaired skill',skill:'review',objective:'Check the repaired repertoire skill on another day and apply it to one comparable context.',
      teaching:['Immediate repetition can make a passage feel familiar without showing whether the repair is available later. On a later day, attempt the passage before extended rehearsal and record what remains dependable. Steadybar review timing is an organizational heuristic, not a universal scientifically proven interval for every motor skill.','After the fresh attempt, apply the same underlying criterion to a comparable passage if that is safe and appropriate for your instrument. Transfer should change one relevant context rather than simply making the task harder. Teacher guidance is especially important when the new context introduces unfamiliar physical technique.'],
      example:'Later-day test: one fresh attempt of the repaired passage. Observation: entrance retained, exit unstable. Transfer: a second passage with the same type of entrance but different musical material. Compare the same continuity criterion.',
      isolate:'Attempt a previously repaired passage before extended repetition and write what remained available.',apply:'Use the same observable criterion on one comparable teacher-approved or self-selected passage.',isolateProtocol:rep('Later-day repertoire check'),applyProtocol:rep('Comparable-context transfer'),
      checks:['The later-day attempt happened before extensive repetition.','I described what was retained rather than only how confident I felt.','The transfer task used a comparable criterion without inventing unsafe technique.'],question:'What is the role of Steadybar review intervals?',options:['Flexible organization rather than a universal validated schedule','A guaranteed mastery prediction','A requirement to practice through discomfort'],answer:0,explanation:'Spacing effects vary by task and study conditions, so Steadybar treats review timing as adjustable organization rather than a universal law.',
      easier:'Repeat only the original later-day check without adding a transfer passage.',harder:'Compare the same criterion across two different but appropriate passages and identify what context changes the outcome.',mistake:'Repeating the passage many times before the check turns a retention attempt into ordinary warm-up practice.',transfer:'Use later-day checks to decide what to bring back to a teacher, rehearsal or future practice plan.'}),
  ]
};

export const PHASE19_COURSES:readonly Course[]=[drums,guitar,bass,piano,voice,custom];
